fail_fast: true
repos:
- repo: https://github.com/ambv/black
  rev: "22.6.0"
  hooks:
    - id: black
      args: [--experimental-string-processing]
      exclude: venv/
- repo: https://github.com/pycqa/flake8
  rev: "4.0.1"
  hooks:
    - id: flake8
      additional_dependencies: [
        flake8-blind-except,
        flake8-bugbear,
        flake8-builtins,
        flake8-comprehensions,
        flake8-debugger,
        flake8-docstrings,
        flake8-isort,
        flake8-quotes,
        flake8-string-format
      ]
      args: [--ignore=W503]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]